### PR TITLE
Add PR_{GET,SET}_NO_NEW_PRIVS to prevent execve from granting privs

### PR DESCRIPTION
**Pull request by codyf86**
With this set, a lot of dangerous operations (chroot, unshare, etc)
become a lot less dangerous because there is no possibility of
subverting privileged binaries.

This patch completely breaks apparmor.  Someone who understands (and
uses) apparmor should fix it or at least give me a hint.

### CODE REVIEW

**Comment by codyf86** [comment]
Added proper authorship.  Fixes PR_SET_NO_NEW_PRIVS: 'Is your kernel compiled correctly?' Error.

You don't have to merge it in to your repo. :)  Just letting you know here is the fix for that error.

**Comment by kumajaya** [comment]
This patch optional for now. References: http://source.android.com/devices/tech/security/enhancements43.html and https://github.com/CyanogenMod/android_dalvik/blob/cm-10.2/vm/Init.cpp .

**Comment by codyf86** [comment]
Yup,

Just letting you know I got it merged and working if you ever need it.  Currently the kernel is giving this
error and I got tired of seeing it in my logcats. lol :)

That and for the merge back to CM, Jiangyi just told me to make sure I had the authorship correct,
that's why there were two of them, sorry about that.

**Comment by codyf86** [comment]
Actually I don't think it's working without this patch Ketut, it says it requires linux kernel version 3.5+ and were using kernel version 3.0.31.

NO_NEW_PRIVS. Android zygote now uses prctl(PR_SET_NO_NEW_PRIVS) to block addition of new privileges prior to execution application code. This prevents Android applications from performing operations which can elevate privileges via execve. (This requires Linux kernel version 3.5 or greater) <=====

**Pull request closed without merging**
